#!/bin/bash
# Helper script to regenerate bibtex-data.js from publications.bib
# Usage: cd publications && ./update-bibtex.sh

echo "Regenerating bibtex-data.js from publications.bib..."

cat publications.bib | sed 's/\\/\\\\/g' | sed "s/'/\\\\'/g" | awk 'BEGIN {print "// Auto-generated from publications/publications.bib"; print "// DO NOT EDIT THIS FILE DIRECTLY - Edit publications/publications.bib instead"; print "// Run: cd publications && ./update-bibtex.sh to regenerate this file"; print ""; print "const BIBTEX_DATA = \`"} {print} END {print "\`;"}' > ../js/bibtex-data.js

echo "Done! js/bibtex-data.js has been updated."
echo ""
echo "To add new publications:"
echo "1. Edit publications/publications.bib to add BibTeX entries"
echo "2. Run: cd publications && ./update-bibtex.sh"
echo "3. Open publications.html in your browser to see the changes"
